version: '3'

services:
  php-nginx:
    image: laptrinhcomvn/php-nginx73:latest
    container_name: lt_php_nginx
    environment:
      - ENABLE_IPV6=true
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
    #  - ./nginx/log:/var/log/nginx
    #  - ./nginx/conf.d:/etc/nginx/conf.d
    #  - ./src:/usr/www/html
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - /Volumes/WORK/PROJECTS/MCLASS/SRC/mclass.vn.conf:/etc/nginx/sites-enabled/mclass.vn.conf
      - /Volumes/WORK/PROJECTS/MCLASS/SRC/mclass_v1.2:/usr/www/src/mclass
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: lt_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=TVUhnqbgL6kTZ4VT
    volumes:
      - ./mysql/mysql_cnf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/data:/var/lib/mysql
    ports:
      - '3306:3306'


